---
swagger: "2.0"
info:
  description: "Projects REST Endpoints"
  version: "v1"
  title: "Projects API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9082"
basePath: "/tms-projects/v1"
tags:
- name: "projects"
schemes:
- "http"
paths:
  /projects:
    post:
      tags:
      - "projects"
      summary: "Create Project"
      description: ""
      operationId: "add"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Project Model"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Project"
        201:
          description: "Project Added"
        400:
          description: "Bad Request: Invalid input"
  /projects/health:
    get:
      tags:
      - "projects"
      summary: "API Health Check"
      description: ""
      operationId: "checkHealth"
      produces:
      - "application/json"
      - "application/xml"
      parameters: []
      responses:
        default:
          description: "successful operation"
definitions:
  Comment:
    type: "object"
    properties:
      commentId:
        type: "integer"
        format: "int64"
      crteById:
        type: "string"
      crteByName:
        type: "string"
      crteTmst:
        type: "string"
        format: "date-time"
      text:
        type: "string"
      updtTmst:
        type: "string"
        format: "date-time"
      ticket:
        $ref: "#/definitions/Ticket"
  Project:
    type: "object"
    properties:
      projectId:
        type: "string"
      description:
        type: "string"
      projectName:
        type: "string"
      tickets:
        type: "array"
        uniqueItems: true
        items:
          $ref: "#/definitions/Ticket"
  Ticket:
    type: "object"
    properties:
      ticketId:
        type: "integer"
        format: "int64"
      assignedUser:
        type: "string"
      crteTmst:
        type: "string"
        format: "date-time"
      description:
        type: "string"
      ticketTitle:
        type: "string"
      updtTmst:
        type: "string"
        format: "date-time"
      comments:
        type: "array"
        uniqueItems: true
        items:
          $ref: "#/definitions/Comment"
      project:
        $ref: "#/definitions/Project"
